### PR TITLE
Add ci

### PR DESCRIPTION
**Pull request by brentmclark**
closes: #39 

- [x] Test
- [x] Lint
- [x] Build
- [ ] Deploy

---

@crysfel I don't know anything about how this code is deployed.  Would you like me to drop that part off of this PR so you can wire it up?  Alternatively, I'm happy to learn more so I can automate the deploys myself, or pair up on the implementation.  Whatever you're comfortable with.

### CODE REVIEW

**Comment by crysfel** [comment]
We can pair and move the deployment to the CI

**Comment by brentmclark** [comment]
Let's pair up on that soon, but get this one merged so we can stop the bleeding on `tslint`.  Sound good?

**Comment by moshfeu** [comment]
LGTM. Just waiting for the deploy step.

**Comment by moshfeu** [comment]
@crysfel, @brentmclark did you finish also the deploy step?

**Comment by crysfel** [comment]
No yet

**Pull request merged**
