### PR TITLE
fix(mentorships): filter deleted users

### LINKED ISSUE #188: mentorships//requests returns 500 when the mentee delete their account
When a user submit a mentorship request and them delete their account,
the mentorships/[userID]/requests returns 500.

Probably because it tries to retrieve the user.

### PR DESCRIPTION
**Pull request by moshfeu**
fix #188

### CODE REVIEW

**Comment by brentmclark** [comment]
🎉  Mosh!

Great work and nice test!

I see you're filtering out the mentorships with missing mentors and/or mentees at the point where we construct the DTO for returning a response from that API endpoint.  While this addresses the immediate issue properly, it leaves the root of the problem intact.  That is to say, we should probably filter out these orphaned mentorships inside of the service (a.k.a. at the database query) instead of at the time we're constructing the response.  Most likely this issue with orphaned mentorships will impact other code paths that _also_ use the service to get a list of mentorships.  So, fixing the issue as close to the database as possible will be more helpful long term.

How do you feel about filtering out these orphaned records inside of `MentorshipSerce.findMentorshipsByUser` instead, Mosh?

---

As a separate task (i.e. not to be dealt with right now) we may also want to consider using logical deletes for user accounts instead of leaving orphaned records around in the DB.  Or we could delete all related records at the time we delete the user record (similar to cascading deletes).  Either approach will work.

**Review by brentmclark — APPROVED** [review]
Looks good to me!  I really like the attention paid to the UX of all of this.  Letting the missing mentor or mentee come through so the UI can handle the messaging.  Great work!

**Comment by crysfel** [comment]
It looks to me, the root of the problem is the fact that we are not removing requests when removing the user from the database, I think we should do that to prevent this from happening.

**Review by crysfel — APPROVED** [review]

**Comment by moshfeu** [comment]
Actually I like the idea of showing"user was removed rather than hidding. This way users won't surprised that their pair just disappeared.

**Pull request merged**
